import "dotenv/config"; 
import { db } from "../app/lib/db/drizzle";
import { artists, venues, events, user } from "../app/lib/db/schema";

async function seed() {
  console.log("🌱 Seeding database...");

  try {
    // NETTOYER LES DONNÉES EXISTANTES
    console.log("🗑️  Cleaning existing data...");
    await db.delete(events);
    await db.delete(venues);
    await db.delete(artists);
    console.log("✅ Old data cleaned");

    // 1. Créer des artistes underground
    console.log("📝 Creating artists...");
    const [
      pépite, juniore, vendredi, lewsberg, fontaines,
      wetneg, jaguwar, meskerem, papooz, requin,
      agar, foudre, suzane, orchestre, yseult
    ] = await db
      .insert(artists)
      .values([
        {
          name: "Pépite",
          genre: "Indie Pop",
          imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
          spotifyUrl: "https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb",
          instagramUrl: "https://instagram.com/pepiteband",
          bio: "Groupe indie pop français aux mélodies solaires et textes poétiques.",
        },
        {
          name: "Juniore",
          genre: "Yé-yé moderne",
          imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
          spotifyUrl: "https://open.spotify.com/artist/2QsynagSdAqZj3U9HgDzjD",
          instagramUrl: "https://instagram.com/junioreband",
          bio: "Groupe féminin parisien mêlant yé-yé vintage et psychédélisme moderne.",
        },
        {
          name: "Vendredi sur Mer",
          genre: "Dream Pop",
          imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
          spotifyUrl: "https://open.spotify.com/artist/6FXMGKw1lh4TkHWRsLZz1f",
          instagramUrl: "https://instagram.com/vendredisurmer",
          bio: "Artiste franco-suisse au style rêveur et envoûtant.",
        },
        {
          name: "Lewsberg",
          genre: "Post-Punk",
          imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
          spotifyUrl: "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x",
          instagramUrl: "https://instagram.com/lewsbergband",
          bio: "Groupe post-punk néerlandais au son minimaliste et hypnotique.",
        },
        {
          name: "Fontaines D.C.",
          genre: "Post-Punk/Rock",
          imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4",
          spotifyUrl: "https://open.spotify.com/artist/2xe8IXgCTpwHE3eA9hTs3p",
          instagramUrl: "https://instagram.com/fontainesdublin",
          bio: "Groupe irlandais de post-punk énergique et poétique.",
        },
        {
          name: "Wet Leg",
          genre: "Indie Rock",
          imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae",
          spotifyUrl: "https://open.spotify.com/artist/12uPNu1rM8LKm9j9gAZcMB",
          instagramUrl: "https://instagram.com/wet_leg",
          bio: "Duo britannique indie rock à l'humour décalé.",
        },
        {
          name: "Jaguwar",
          genre: "Garage Rock",
          imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad",
          spotifyUrl: "https://open.spotify.com/artist/1234567890",
          instagramUrl: "https://instagram.com/jaguwarband",
          bio: "Groupe de garage rock français brut et énergique.",
        },
        {
          name: "Meskerem Mees",
          genre: "Folk/Indie",
          imageUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
          spotifyUrl: "https://open.spotify.com/artist/6wPhSqRCkxNnGFT5slLmLJ",
          instagramUrl: "https://instagram.com/meskeremmees",
          bio: "Auteure-compositrice belge aux mélodies folk intimistes.",
        },
        {
          name: "Papooz",
          genre: "Soft Rock",
          imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
          spotifyUrl: "https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm",
          instagramUrl: "https://instagram.com/papoozmusic",
          bio: "Duo français de soft rock aux influences 70's et lo-fi.",
        },
        {
          name: "Requin Chagrin",
          genre: "Indie Pop",
          imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
          spotifyUrl: "https://open.spotify.com/artist/4wLaiR8Z5Z9Nx2dJ1qZ5qJ",
          instagramUrl: "https://instagram.com/requinchagrin",
          bio: "Groupe indie pop français aux textes mélancoliques et touchants.",
        },
        {
          name: "Agar Agar",
          genre: "Électro/Synth-pop",
          imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
          spotifyUrl: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
          instagramUrl: "https://instagram.com/agaragar.music",
          bio: "Duo français d'électro-pop dansante et colorée.",
        },
        {
          name: "Foudre!",
          genre: "Garage/Punk",
          imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
          spotifyUrl: "https://open.spotify.com/artist/5Z9K8Z0Z0Z0Z0Z0Z0Z0Z0Z",
          instagramUrl: "https://instagram.com/foudreband",
          bio: "Groupe garage punk français explosif et sans compromis.",
        },
        {
          name: "Suzane",
          genre: "Pop/R&B",
          imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae",
          spotifyUrl: "https://open.spotify.com/artist/6LqNN22kT3074XbTVUrhzX",
          instagramUrl: "https://instagram.com/suzane",
          bio: "Chanteuse française de pop/R&B à l'univers coloré et dansant.",
        },
        {
          name: "L'Impératrice",
          genre: "Nu-Disco/Funk",
          imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad",
          spotifyUrl: "https://open.spotify.com/artist/4rKWScFWSebbPX1wbjSmjw",
          instagramUrl: "https://instagram.com/limperatrice",
          bio: "Groupe parisien de nu-disco et funk sophistiqué.",
        },
        {
          name: "Yseult",
          genre: "Soul/R&B",
          imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
          spotifyUrl: "https://open.spotify.com/artist/7bE5JVLRwNOtZBv5bRowaU",
          instagramUrl: "https://instagram.com/yseult",
          bio: "Chanteuse française de soul et R&B à la voix puissante.",
        },
      ])
      .returning();

    console.log(`✅ 15 artistes underground/indépendants créés`);

    // 2. Créer des petites salles à Paris et région parisienne
    console.log("📝 Creating venues...");
    const [
      pointEphemere, maroquinerie, flecheOr, popup, petitBain,
      supersonic, glazart, gibus, silencio, batofar,
      djoon, concreteVenue, rex, nouveauCasino, trabendo,
      bercyVillage, mecanique, laVilla, laBouleNoire, moulinRouge
    ] = await db
      .insert(venues)
      .values([
        {
          name: "Le Point Ephémère",
          address: "200 Quai de Valmy",
          city: "Paris",
          postalCode: "75010",
          latitude: 48.875556,
          longitude: 2.367778,
          capacity: 300,
        },
        {
          name: "La Maroquinerie",
          address: "23 Rue Boyer",
          city: "Paris",
          postalCode: "75020",
          latitude: 48.872222,
          longitude: 2.389167,
          capacity: 600,
        },
        {
          name: "La Flèche d'Or",
          address: "102 bis Rue de Bagnolet",
          city: "Paris",
          postalCode: "75020",
          latitude: 48.856389,
          longitude: 2.404444,
          capacity: 450,
        },
        {
          name: "Pop-Up du Label",
          address: "15 Rue Customhouse",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.858611,
          longitude: 2.372778,
          capacity: 250,
        },
        {
          name: "Petit Bain",
          address: "7 Port de la Gare",
          city: "Paris",
          postalCode: "75013",
          latitude: 48.833889,
          longitude: 2.377222,
          capacity: 350,
        },
        {
          name: "Supersonic",
          address: "9 Rue Biscornet",
          city: "Paris",
          postalCode: "75012",
          latitude: 48.850278,
          longitude: 2.370556,
          capacity: 400,
        },
        {
          name: "Glazart",
          address: "7-15 Avenue de la Porte de la Villette",
          city: "Paris",
          postalCode: "75019",
          latitude: 48.896944,
          longitude: 2.387778,
          capacity: 800,
        },
        {
          name: "Le Gibus",
          address: "18 Rue du Faubourg du Temple",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.868333,
          longitude: 2.367222,
          capacity: 500,
        },
        {
          name: "Silencio",
          address: "142 Rue Montmartre",
          city: "Paris",
          postalCode: "75002",
          latitude: 48.869444,
          longitude: 2.342778,
          capacity: 300,
        },
        {
          name: "Batofar",
          address: "11 Quai François Mauriac",
          city: "Paris",
          postalCode: "75013",
          latitude: 48.832778,
          longitude: 2.376389,
          capacity: 350,
        },
        {
          name: "Djoon",
          address: "22-24 Boulevard Vincent Auriol",
          city: "Paris",
          postalCode: "75013",
          latitude: 48.835278,
          longitude: 2.367500,
          capacity: 400,
        },
        {
          name: "Concrete",
          address: "69 Port de la Rapée",
          city: "Paris",
          postalCode: "75012",
          latitude: 48.842500,
          longitude: 2.374167,
          capacity: 500,
        },
        {
          name: "Le Rex Club",
          address: "5 Boulevard Poissonnière",
          city: "Paris",
          postalCode: "75002",
          latitude: 48.871111,
          longitude: 2.346944,
          capacity: 650,
        },
        {
          name: "Le Nouveau Casino",
          address: "109 Rue Oberkampf",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.866389,
          longitude: 2.381667,
          capacity: 400,
        },
        {
          name: "Le Trabendo",
          address: "211 Avenue Jean Jaurès",
          city: "Paris",
          postalCode: "75019",
          latitude: 48.894167,
          longitude: 2.393333,
          capacity: 700,
        },
        {
          name: "Le Backstage by the Mill",
          address: "8 Boulevard de Bercy",
          city: "Paris",
          postalCode: "75012",
          latitude: 48.839722,
          longitude: 2.379444,
          capacity: 350,
        },
        {
          name: "La Mécanique Ondulatoire",
          address: "8 Passage Thiéré",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.855833,
          longitude: 2.382500,
          capacity: 280,
        },
        {
          name: "La Java",
          address: "105 Rue du Faubourg du Temple",
          city: "Paris",
          postalCode: "75010",
          latitude: 48.869722,
          longitude: 2.371389,
          capacity: 350,
        },
        {
          name: "La Boule Noire",
          address: "120 Boulevard de Rochechouart",
          city: "Paris",
          postalCode: "75018",
          latitude: 48.883056,
          longitude: 2.340556,
          capacity: 500,
        },
        {
          name: "L'International",
          address: "5-7 Rue Moret",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.867500,
          longitude: 2.379722,
          capacity: 200,
        },
      ])
      .returning();

    console.log(`✅ 20 petites salles parisiennes créées`);

    // 3. Créer des événements
    console.log("📝 Creating events...");
    const createdEvents = await db.insert(events).values([
      {
        slug: "pepite-point-ephemere-2026",
        title: "Pépite - Perspectives Tour",
        description: "Concert intimiste de Pépite au Point Ephémère.",
        imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        artistId: pépite.id,
        venueId: pointEphemere.id,
        eventDate: new Date("2026-02-20"),
        eventTime: "20:30",
        price: 18.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "juniore-maroquinerie-2026",
        title: "Juniore - Soirée Yé-Yé",
        description: "Soirée psychédélique avec Juniore à La Maroquinerie.",
        imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        artistId: juniore.id,
        venueId: maroquinerie.id,
        eventDate: new Date("2026-03-15"),
        eventTime: "21:00",
        price: 20.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "vendredi-fleche-or-2026",
        title: "Vendredi sur Mer - Dream Session",
        description: "Concert dream pop envoûtant à La Flèche d'Or.",
        imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
        artistId: vendredi.id,
        venueId: flecheOr.id,
        eventDate: new Date("2026-04-10"),
        eventTime: "20:00",
        price: 22.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "lewsberg-popup-2026",
        title: "Lewsberg - Post-Punk Night",
        description: "Concert post-punk minimaliste au Pop-Up du Label.",
        imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        artistId: lewsberg.id,
        venueId: popup.id,
        eventDate: new Date("2026-03-28"),
        eventTime: "21:00",
        price: 16.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "fontaines-trabendo-2026",
        title: "Fontaines D.C. - Paris Live",
        description: "Le groupe irlandais débarque au Trabendo.",
        imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4",
        artistId: fontaines.id,
        venueId: trabendo.id,
        eventDate: new Date("2026-05-15"),
        eventTime: "20:30",
        price: 25.0,
        ticketUrl: "https://www.seetickets.fr",
        status: "upcoming",
      },
      {
        slug: "wetleg-nouveau-casino-2026",
        title: "Wet Leg - Indie Rock Party",
        description: "Concert indie rock décontracté au Nouveau Casino.",
        imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae",
        artistId: wetneg.id,
        venueId: nouveauCasino.id,
        eventDate: new Date("2026-04-22"),
        eventTime: "20:00",
        price: 23.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "jaguwar-gibus-2026",
        title: "Jaguwar - Garage Rock Explosion",
        description: "Concert garage rock énergique au Gibus.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad",
        artistId: jaguwar.id,
        venueId: gibus.id,
        eventDate: new Date("2026-03-05"),
        eventTime: "21:30",
        price: 15.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "meskerem-petit-bain-2026",
        title: "Meskerem Mees - Acoustic Session",
        description: "Concert folk intimiste sur le Petit Bain.",
        imageUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
        artistId: meskerem.id,
        venueId: petitBain.id,
        eventDate: new Date("2026-04-18"),
        eventTime: "20:30",
        price: 19.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "papooz-silencio-2026",
        title: "Papooz - Soft Rock Night",
        description: "Soirée soft rock vintage au Silencio.",
        imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        artistId: papooz.id,
        venueId: silencio.id,
        eventDate: new Date("2026-05-08"),
        eventTime: "21:00",
        price: 20.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "requin-maroquinerie-2026",
        title: "Requin Chagrin - Mélancolie Tour",
        description: "Concert indie pop mélancolique à La Maroquinerie.",
        imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        artistId: requin.id,
        venueId: maroquinerie.id,
        eventDate: new Date("2026-02-28"),
        eventTime: "20:00",
        price: 18.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "agar-agar-glazart-2026",
        title: "Agar Agar - Synth-Pop Party",
        description: "Soirée électro-pop dansante au Glazart.",
        imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
        artistId: agar.id,
        venueId: glazart.id,
        eventDate: new Date("2026-03-20"),
        eventTime: "22:00",
        price: 20.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "foudre-boule-noire-2026",
        title: "Foudre! - Punk Explosion",
        description: "Concert garage punk explosif à La Boule Noire.",
        imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        artistId: foudre.id,
        venueId: laBouleNoire.id,
        eventDate: new Date("2026-04-05"),
        eventTime: "21:00",
        price: 17.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "suzane-trabendo-2026",
        title: "Suzane - Pop Colorée",
        description: "Show pop/R&B énergique au Trabendo.",
        imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae",
        artistId: suzane.id,
        venueId: trabendo.id,
        eventDate: new Date("2026-05-22"),
        eventTime: "20:00",
        price: 23.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "imperatrice-batofar-2026",
        title: "L'Impératrice - Disco Funk Night",
        description: "Soirée nu-disco sophistiquée sur le Batofar.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad",
        artistId: orchestre.id,
        venueId: batofar.id,
        eventDate: new Date("2026-06-10"),
        eventTime: "21:30",
        price: 24.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "yseult-nouveau-casino-2026",
        title: "Yseult - Soul Experience",
        description: "Concert soul puissant au Nouveau Casino.",
        imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        artistId: yseult.id,
        venueId: nouveauCasino.id,
        eventDate: new Date("2026-05-28"),
        eventTime: "20:30",
        price: 22.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "pepite-mecanique-2026",
        title: "Pépite - Session Intimiste",
        description: "Concert acoustique à La Mécanique Ondulatoire.",
        imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        artistId: pépite.id,
        venueId: mecanique.id,
        eventDate: new Date("2026-03-12"),
        eventTime: "21:00",
        price: 16.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "vendredi-supersonic-2026",
        title: "Vendredi sur Mer - Nuit Rêveuse",
        description: "Performance dream pop au Supersonic.",
        imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
        artistId: vendredi.id,
        venueId: supersonic.id,
        eventDate: new Date("2026-04-25"),
        eventTime: "20:30",
        price: 21.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "papooz-popup-2026",
        title: "Papooz - Lo-Fi Evening",
        description: "Concert lo-fi chaleureux au Pop-Up du Label.",
        imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        artistId: papooz.id,
        venueId: popup.id,
        eventDate: new Date("2026-05-16"),
        eventTime: "20:00",
        price: 17.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "agar-agar-djoon-2026",
        title: "Agar Agar - Electronic Night",
        description: "DJ set électro au Djoon.",
        imageUrl: "https://images.unsplash.com/photo-1516280440614-37939bbacd81",
        artistId: agar.id,
        venueId: djoon.id,
        eventDate: new Date("2026-06-05"),
        eventTime: "23:00",
        price: 18.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "imperatrice-concrete-2026",
        title: "L'Impératrice - Concrete Session",
        description: "Soirée funk sur le Concrete.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad",
        artistId: orchestre.id,
        venueId: concreteVenue.id,
        eventDate: new Date("2026-06-20"),
        eventTime: "22:00",
        price: 25.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "juniore-fleche-or-2026",
        title: "Juniore - Vintage Night",
        description: "Concert yé-yé psychédélique à La Flèche d'Or.",
        imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        artistId: juniore.id,
        venueId: flecheOr.id,
        eventDate: new Date("2026-03-25"),
        eventTime: "20:30",
        price: 19.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "fontaines-glazart-2026",
        title: "Fontaines D.C. - Post-Punk Session",
        description: "Concert post-punk intense au Glazart.",
        imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4",
        artistId: fontaines.id,
        venueId: glazart.id,
        eventDate: new Date("2026-05-20"),
        eventTime: "21:00",
        price: 24.0,
        ticketUrl: "https://www.seetickets.fr",
        status: "upcoming",
      },
      {
        slug: "wetleg-gibus-2026",
        title: "Wet Leg - Indie Party",
        description: "Soirée indie rock au Gibus.",
        imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae",
        artistId: wetneg.id,
        venueId: gibus.id,
        eventDate: new Date("2026-04-30"),
        eventTime: "21:30",
        price: 21.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "meskerem-point-ephemere-2026",
        title: "Meskerem Mees - Folk Intimiste",
        description: "Concert folk acoustique au Point Ephémère.",
        imageUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a",
        artistId: meskerem.id,
        venueId: pointEphemere.id,
        eventDate: new Date("2026-05-05"),
        eventTime: "20:00",
        price: 18.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "requin-petit-bain-2026",
        title: "Requin Chagrin - Soirée Mélancolique",
        description: "Concert indie pop sur le Petit Bain.",
        imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f",
        artistId: requin.id,
        venueId: petitBain.id,
        eventDate: new Date("2026-03-18"),
        eventTime: "20:30",
        price: 19.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "suzane-glazart-2026",
        title: "Suzane - R&B Show",
        description: "Show pop/R&B coloré au Glazart.",
        imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae",
        artistId: suzane.id,
        venueId: glazart.id,
        eventDate: new Date("2026-06-02"),
        eventTime: "21:00",
        price: 22.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "yseult-batofar-2026",
        title: "Yseult - Soul Night",
        description: "Concert soul intimiste sur le Batofar.",
        imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
        artistId: yseult.id,
        venueId: batofar.id,
        eventDate: new Date("2026-06-12"),
        eventTime: "20:30",
        price: 21.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "foudre-international-2026",
        title: "Foudre! - Punk Intimiste",
        description: "Concert garage punk dans la petite salle de L'International.",
        imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        artistId: foudre.id,
        venueId: moulinRouge.id,
        eventDate: new Date("2026-04-12"),
        eventTime: "21:30",
        price: 14.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "lewsberg-mecanique-2026",
        title: "Lewsberg - Minimaliste Session",
        description: "Concert post-punk minimaliste à La Mécanique Ondulatoire.",
        imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
        artistId: lewsberg.id,
        venueId: mecanique.id,
        eventDate: new Date("2026-04-08"),
        eventTime: "21:00",
        price: 15.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "jaguwar-fleche-or-2026",
        title: "Jaguwar - Garage Night",
        description: "Concert garage rock brut à La Flèche d'Or.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad",
        artistId: jaguwar.id,
        venueId: flecheOr.id,
        eventDate: new Date("2026-03-22"),
        eventTime: "21:00",
        price: 16.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
    ]).returning();

    console.log(`✅ ${createdEvents.length} événements underground créés à Paris`);

    console.log("\n🎉 Seeding completed successfully!");
    console.log(`📊 Résumé:`);
    console.log(`   - 15 artistes underground/indépendants (français et internationaux)`);
    console.log(`   - 20 petites salles parisiennes`);
    console.log(`   - ${createdEvents.length} événements`);
    console.log(`   - Prix des places : 14€ - 25€`);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    throw error;
  }
}

seed()
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });