import "dotenv/config"; 
import { db } from "../app/lib/db/drizzle";
import { artists, venues, events, user } from "../app/lib/db/schema";

async function seed() {
  console.log("🌱 Seeding database...");

  try {
    // NETTOYER LES DONNÉES EXISTANTES
    console.log("🗑️  Cleaning existing data...");
    await db.delete(events);
    await db.delete(venues);
    await db.delete(artists);
    console.log("✅ Old data cleaned");

    // 1. Créer des artistes underground
    console.log("📝 Creating artists...");
    const [
      pépite, juniore, vendredi, lewsberg, fontaines,
      wetneg, jaguwar, meskerem, papooz, requin,
      agar, foudre, suzane, orchestre, yseult,
      // Nouveaux artistes
      molly, idles, blackMidi, squid, shame,
      cocaine, clara, therapie, pomme, angele
    ] = await db
      .insert(artists)
      .values([
        {
          name: "Pépite",
          genre: "Indie Pop",
          imageUrl: "https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=800",
          spotifyUrl: "https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb",
          instagramUrl: "https://instagram.com/pepiteband",
          bio: "Groupe indie pop français aux mélodies solaires et textes poétiques.",
        },
        {
          name: "Juniore",
          genre: "Yé-yé moderne",
          imageUrl: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800",
          spotifyUrl: "https://open.spotify.com/artist/2QsynagSdAqZj3U9HgDzjD",
          instagramUrl: "https://instagram.com/junioreband",
          bio: "Groupe féminin parisien mêlant yé-yé vintage et psychédélisme moderne.",
        },
        {
          name: "Vendredi sur Mer",
          genre: "Dream Pop",
          imageUrl: "https://images.unsplash.com/photo-1485120750507-a3bf477acd63?w=800",
          spotifyUrl: "https://open.spotify.com/artist/6FXMGKw1lh4TkHWRsLZz1f",
          instagramUrl: "https://instagram.com/vendredisurmer",
          bio: "Artiste franco-suisse au style rêveur et envoûtant.",
        },
        {
          name: "Lewsberg",
          genre: "Post-Punk",
          imageUrl: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=800",
          spotifyUrl: "https://open.spotify.com/artist/5K4W6rqBFWDnAN6FQUkS6x",
          instagramUrl: "https://instagram.com/lewsbergband",
          bio: "Groupe post-punk néerlandais au son minimaliste et hypnotique.",
        },
        {
          name: "Fontaines D.C.",
          genre: "Post-Punk/Rock",
          imageUrl: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800",
          spotifyUrl: "https://open.spotify.com/artist/2xe8IXgCTpwHE3eA9hTs3p",
          instagramUrl: "https://instagram.com/fontainesdublin",
          bio: "Groupe irlandais de post-punk énergique et poétique.",
        },
        {
          name: "Wet Leg",
          genre: "Indie Rock",
          imageUrl: "https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?w=800",
          spotifyUrl: "https://open.spotify.com/artist/12uPNu1rM8LKm9j9gAZcMB",
          instagramUrl: "https://instagram.com/wet_leg",
          bio: "Duo britannique indie rock à l'humour décalé.",
        },
        {
          name: "Jaguwar",
          genre: "Garage Rock",
          imageUrl: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=800",
          spotifyUrl: "https://open.spotify.com/artist/1234567890",
          instagramUrl: "https://instagram.com/jaguwarband",
          bio: "Groupe de garage rock français brut et énergique.",
        },
        {
          name: "Meskerem Mees",
          genre: "Folk/Indie",
          imageUrl: "https://images.unsplash.com/photo-1660150509350-ff505601d094?w=800",
          spotifyUrl: "https://open.spotify.com/artist/6wPhSqRCkxNnGFT5slLmLJ",
          instagramUrl: "https://instagram.com/meskeremmees",
          bio: "Auteure-compositrice belge aux mélodies folk intimistes.",
        },
        {
          name: "Papooz",
          genre: "Soft Rock",
          imageUrl: "https://images.unsplash.com/photo-1445985543470-41fba5c3144a?w=800",
          spotifyUrl: "https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm",
          instagramUrl: "https://instagram.com/papoozmusic",
          bio: "Duo français de soft rock aux influences 70's et lo-fi.",
        },
        {
          name: "Requin Chagrin",
          genre: "Indie Pop",
          imageUrl: "https://images.unsplash.com/photo-1477233534935-f5e6fe7c1159?w=800",
          spotifyUrl: "https://open.spotify.com/artist/4wLaiR8Z5Z9Nx2dJ1qZ5qJ",
          instagramUrl: "https://instagram.com/requinchagrin",
          bio: "Groupe indie pop français aux textes mélancoliques et touchants.",
        },
        {
          name: "Agar Agar",
          genre: "Électro/Synth-pop",
          imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800",
          spotifyUrl: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of",
          instagramUrl: "https://instagram.com/agaragar.music",
          bio: "Duo français d'électro-pop dansante et colorée.",
        },
        {
          name: "Foudre!",
          genre: "Garage/Punk",
          imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800",
          spotifyUrl: "https://open.spotify.com/artist/5Z9K8Z0Z0Z0Z0Z0Z0Z0Z0Z",
          instagramUrl: "https://instagram.com/foudreband",
          bio: "Groupe garage punk français explosif et sans compromis.",
        },
        {
          name: "Suzane",
          genre: "Pop/R&B",
          imageUrl: "https://images.unsplash.com/photo-1510731491328-7363eecd7b2d?w=800",
          spotifyUrl: "https://open.spotify.com/artist/6LqNN22kT3074XbTVUrhzX",
          instagramUrl: "https://instagram.com/suzane",
          bio: "Chanteuse française de pop/R&B à l'univers coloré et dansant.",
        },
        {
          name: "L'Impératrice",
          genre: "Nu-Disco/Funk",
          imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800",
          spotifyUrl: "https://open.spotify.com/artist/4rKWScFWSebbPX1wbjSmjw",
          instagramUrl: "https://instagram.com/limperatrice",
          bio: "Groupe parisien de nu-disco et funk sophistiqué.",
        },
        {
          name: "Yseult",
          genre: "Soul/R&B",
          imageUrl: "https://images.unsplash.com/photo-1515191107209-c28698631303?w=800",
          spotifyUrl: "https://open.spotify.com/artist/7bE5JVLRwNOtZBv5bRowaU",
          instagramUrl: "https://instagram.com/yseult",
          bio: "Chanteuse française de soul et R&B à la voix puissante.",
        },
        // NOUVEAUX ARTISTES
        {
          name: "Molly Nilsson",
          genre: "Synth-Pop",
          imageUrl: "https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=800",
          spotifyUrl: "https://open.spotify.com/artist/1a2b3c4d5e",
          instagramUrl: "https://instagram.com/mollynilsson",
          bio: "Artiste suédoise de synth-pop minimaliste et mélancolique.",
        },
        {
          name: "IDLES",
          genre: "Punk Rock",
          imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
          spotifyUrl: "https://open.spotify.com/artist/6GhQV",
          instagramUrl: "https://instagram.com/idlesband",
          bio: "Groupe britannique de punk rock viscéral et politique.",
        },
        {
          name: "Black Midi",
          genre: "Experimental Rock",
          imageUrl: "https://images.unsplash.com/photo-1484876065684-b683cf17d276?w=800",
          spotifyUrl: "https://open.spotify.com/artist/1a2b3c",
          instagramUrl: "https://instagram.com/blackmidiband",
          bio: "Groupe expérimental londonien au rock mathématique et chaotique.",
        },
        {
          name: "Squid",
          genre: "Art Rock",
          imageUrl: "https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=800",
          spotifyUrl: "https://open.spotify.com/artist/squid123",
          instagramUrl: "https://instagram.com/squidtheband",
          bio: "Groupe britannique d'art rock post-punk innovant.",
        },
        {
          name: "Shame",
          genre: "Post-Punk",
          imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
          spotifyUrl: "https://open.spotify.com/artist/shame456",
          instagramUrl: "https://instagram.com/shameband",
          bio: "Groupe post-punk londonien énergique et brut.",
        },
        {
          name: "Cocaine Piss",
          genre: "Noise Rock",
          imageUrl: "https://images.unsplash.com/photo-1558443957-842080c8273c?w=800",
          spotifyUrl: "https://open.spotify.com/artist/coke789",
          instagramUrl: "https://instagram.com/cocainepiss",
          bio: "Trio belge de noise rock explosif et décalé.",
        },
        {
          name: "Clara Luciani",
          genre: "Pop Française",
          imageUrl: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800",
          spotifyUrl: "https://open.spotify.com/artist/clara123",
          instagramUrl: "https://instagram.com/claraluciani",
          bio: "Chanteuse française pop aux textes forts et à la voix unique.",
        },
        {
          name: "Therapie TAXI",
          genre: "Electro-Pop",
          imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800",
          spotifyUrl: "https://open.spotify.com/artist/therapie",
          instagramUrl: "https://instagram.com/therapietaxi",
          bio: "Duo français d'electro-pop décomplexé et dansant.",
        },
        {
          name: "Pomme",
          genre: "Chanson/Folk",
          imageUrl: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=800",
          spotifyUrl: "https://open.spotify.com/artist/pomme789",
          instagramUrl: "https://instagram.com/pommemusic",
          bio: "Auteure-compositrice française à la voix douce et poétique.",
        },
        {
          name: "Angèle",
          genre: "Pop",
          imageUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800",
          spotifyUrl: "https://open.spotify.com/artist/angele456",
          instagramUrl: "https://instagram.com/angele_vl",
          bio: "Chanteuse belge pop engagée et énergique.",
        },
      ])
      .returning();

    console.log(`✅ 25 artistes underground/indépendants créés`);

    // 2. Créer des petites salles à Paris et région parisienne
    console.log("📝 Creating venues...");
    const [
      pointEphemere, maroquinerie, flecheOr, popup, petitBain,
      supersonic, glazart, gibus, silencio, batofar,
      djoon, concreteVenue, rex, nouveauCasino, trabendo,
      bercyVillage, mecanique, laJava, laBouleNoire, international,
      // Nouvelles salles
      elysee, cigale, trianon, olympia, zenith,
      gaite, divan, bellevilloise, fleche, badaboum
    ] = await db
      .insert(venues)
      .values([
        {
          name: "Le Point Ephémère",
          address: "200 Quai de Valmy",
          city: "Paris",
          postalCode: "75010",
          latitude: 48.875556,
          longitude: 2.367778,
          capacity: 300,
        },
        {
          name: "La Maroquinerie",
          address: "23 Rue Boyer",
          city: "Paris",
          postalCode: "75020",
          latitude: 48.872222,
          longitude: 2.389167,
          capacity: 600,
        },
        {
          name: "La Flèche d'Or",
          address: "102 bis Rue de Bagnolet",
          city: "Paris",
          postalCode: "75020",
          latitude: 48.856389,
          longitude: 2.404444,
          capacity: 450,
        },
        {
          name: "Pop-Up du Label",
          address: "15 Rue Customhouse",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.858611,
          longitude: 2.372778,
          capacity: 250,
        },
        {
          name: "Petit Bain",
          address: "7 Port de la Gare",
          city: "Paris",
          postalCode: "75013",
          latitude: 48.833889,
          longitude: 2.377222,
          capacity: 350,
        },
        {
          name: "Supersonic",
          address: "9 Rue Biscornet",
          city: "Paris",
          postalCode: "75012",
          latitude: 48.850278,
          longitude: 2.370556,
          capacity: 400,
        },
        {
          name: "Glazart",
          address: "7-15 Avenue de la Porte de la Villette",
          city: "Paris",
          postalCode: "75019",
          latitude: 48.896944,
          longitude: 2.387778,
          capacity: 800,
        },
        {
          name: "Le Gibus",
          address: "18 Rue du Faubourg du Temple",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.868333,
          longitude: 2.367222,
          capacity: 500,
        },
        {
          name: "Silencio",
          address: "142 Rue Montmartre",
          city: "Paris",
          postalCode: "75002",
          latitude: 48.869444,
          longitude: 2.342778,
          capacity: 300,
        },
        {
          name: "Batofar",
          address: "11 Quai François Mauriac",
          city: "Paris",
          postalCode: "75013",
          latitude: 48.832778,
          longitude: 2.376389,
          capacity: 350,
        },
        {
          name: "Djoon",
          address: "22-24 Boulevard Vincent Auriol",
          city: "Paris",
          postalCode: "75013",
          latitude: 48.835278,
          longitude: 2.367500,
          capacity: 400,
        },
        {
          name: "Concrete",
          address: "69 Port de la Rapée",
          city: "Paris",
          postalCode: "75012",
          latitude: 48.842500,
          longitude: 2.374167,
          capacity: 500,
        },
        {
          name: "Le Rex Club",
          address: "5 Boulevard Poissonnière",
          city: "Paris",
          postalCode: "75002",
          latitude: 48.871111,
          longitude: 2.346944,
          capacity: 650,
        },
        {
          name: "Le Nouveau Casino",
          address: "109 Rue Oberkampf",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.866389,
          longitude: 2.381667,
          capacity: 400,
        },
        {
          name: "Le Trabendo",
          address: "211 Avenue Jean Jaurès",
          city: "Paris",
          postalCode: "75019",
          latitude: 48.894167,
          longitude: 2.393333,
          capacity: 700,
        },
        {
          name: "Le Backstage by the Mill",
          address: "8 Boulevard de Bercy",
          city: "Paris",
          postalCode: "75012",
          latitude: 48.839722,
          longitude: 2.379444,
          capacity: 350,
        },
        {
          name: "La Mécanique Ondulatoire",
          address: "8 Passage Thiéré",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.855833,
          longitude: 2.382500,
          capacity: 280,
        },
        {
          name: "La Java",
          address: "105 Rue du Faubourg du Temple",
          city: "Paris",
          postalCode: "75010",
          latitude: 48.869722,
          longitude: 2.371389,
          capacity: 350,
        },
        {
          name: "La Boule Noire",
          address: "120 Boulevard de Rochechouart",
          city: "Paris",
          postalCode: "75018",
          latitude: 48.883056,
          longitude: 2.340556,
          capacity: 500,
        },
        {
          name: "L'International",
          address: "5-7 Rue Moret",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.867500,
          longitude: 2.379722,
          capacity: 200,
        },
        // NOUVELLES SALLES
        {
          name: "L'Élysée Montmartre",
          address: "72 Boulevard de Rochechouart",
          city: "Paris",
          postalCode: "75018",
          latitude: 48.882500,
          longitude: 2.341111,
          capacity: 1200,
        },
        {
          name: "La Cigale",
          address: "120 Boulevard de Rochechouart",
          city: "Paris",
          postalCode: "75018",
          latitude: 48.882778,
          longitude: 2.340278,
          capacity: 1389,
        },
        {
          name: "Le Trianon",
          address: "80 Boulevard de Rochechouart",
          city: "Paris",
          postalCode: "75018",
          latitude: 48.882222,
          longitude: 2.340833,
          capacity: 800,
        },
        {
          name: "L'Olympia",
          address: "28 Boulevard des Capucines",
          city: "Paris",
          postalCode: "75009",
          latitude: 48.870556,
          longitude: 2.328056,
          capacity: 2000,
        },
        {
          name: "Zénith Paris",
          address: "211 Avenue Jean Jaurès",
          city: "Paris",
          postalCode: "75019",
          latitude: 48.894722,
          longitude: 2.393611,
          capacity: 6300,
        },
        {
          name: "La Gaîté Lyrique",
          address: "3 bis Rue Papin",
          city: "Paris",
          postalCode: "75003",
          latitude: 48.867222,
          longitude: 2.355556,
          capacity: 500,
        },
        {
          name: "Le Divan du Monde",
          address: "75 Rue des Martyrs",
          city: "Paris",
          postalCode: "75018",
          latitude: 48.881944,
          longitude: 2.339167,
          capacity: 350,
        },
        {
          name: "La Bellevilloise",
          address: "19-21 Rue Boyer",
          city: "Paris",
          postalCode: "75020",
          latitude: 48.872500,
          longitude: 2.389722,
          capacity: 600,
        },
        {
          name: "Le Hasard Ludique",
          address: "128 Avenue de Saint-Ouen",
          city: "Paris",
          postalCode: "75018",
          latitude: 48.896389,
          longitude: 2.328333,
          capacity: 400,
        },
        {
          name: "Badaboum",
          address: "2 bis Rue des Taillandiers",
          city: "Paris",
          postalCode: "75011",
          latitude: 48.853611,
          longitude: 2.373056,
          capacity: 300,
        },
      ])
      .returning();

    console.log(`✅ 30 salles parisiennes créées`);

    // 3. Créer des événements
    console.log("📝 Creating events...");
        const createdEvents = await db.insert(events).values([
      {
        slug: "pepite-point-ephemere-2026",
        title: "Pépite - Perspectives Tour",
        description: "Concert intimiste de Pépite au Point Ephémère.",
        imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", // Indie Pop concert
        artistId: pépite.id,
        venueId: pointEphemere.id,
        eventDate: new Date("2026-02-20"),
        eventTime: "20:30",
        price: 18.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "juniore-maroquinerie-2026",
        title: "Juniore - Soirée Yé-Yé",
        description: "Soirée psychédélique avec Juniore à La Maroquinerie.",
        imageUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800", // Vintage/Yé-yé concert
        artistId: juniore.id,
        venueId: maroquinerie.id,
        eventDate: new Date("2026-03-15"),
        eventTime: "21:00",
        price: 20.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "vendredi-fleche-or-2026",
        title: "Vendredi sur Mer - Dream Session",
        description: "Concert dream pop envoûtant à La Flèche d'Or.",
        imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800", // Dream Pop concert
        artistId: vendredi.id,
        venueId: flecheOr.id,
        eventDate: new Date("2026-04-10"),
        eventTime: "20:00",
        price: 22.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "lewsberg-popup-2026",
        title: "Lewsberg - Post-Punk Night",
        description: "Concert post-punk minimaliste au Pop-Up du Label.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800", // Post-Punk concert
        artistId: lewsberg.id,
        venueId: popup.id,
        eventDate: new Date("2026-03-28"),
        eventTime: "21:00",
        price: 16.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "fontaines-trabendo-2026",
        title: "Fontaines D.C. - Paris Live",
        description: "Le groupe irlandais débarque au Trabendo.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800", // Post-Punk/Rock concert
        artistId: fontaines.id,
        venueId: trabendo.id,
        eventDate: new Date("2026-05-15"),
        eventTime: "20:30",
        price: 25.0,
        ticketUrl: "https://www.seetickets.fr",
        status: "upcoming",
      },
      {
        slug: "wetleg-nouveau-casino-2026",
        title: "Wet Leg - Indie Rock Party",
        description: "Concert indie rock décontracté au Nouveau Casino.",
        imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800", // Indie Rock concert
        artistId: wetneg.id,
        venueId: nouveauCasino.id,
        eventDate: new Date("2026-04-22"),
        eventTime: "20:00",
        price: 23.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "jaguwar-gibus-2026",
        title: "Jaguwar - Garage Rock Explosion",
        description: "Concert garage rock énergique au Gibus.",
        imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800", // Garage Rock concert
        artistId: jaguwar.id,
        venueId: gibus.id,
        eventDate: new Date("2026-03-05"),
        eventTime: "21:30",
        price: 15.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "meskerem-petit-bain-2026",
        title: "Meskerem Mees - Acoustic Session",
        description: "Concert folk intimiste sur le Petit Bain.",
        imageUrl: "https://images.unsplash.com/photo-1516450137517-162bfbeb8dba?w=800", // Folk concert
        artistId: meskerem.id,
        venueId: petitBain.id,
        eventDate: new Date("2026-04-18"),
        eventTime: "20:30",
        price: 19.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "papooz-silencio-2026",
        title: "Papooz - Soft Rock Night",
        description: "Soirée soft rock vintage au Silencio.",
        imageUrl: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800", // Soft Rock concert
        artistId: papooz.id,
        venueId: silencio.id,
        eventDate: new Date("2026-05-08"),
        eventTime: "21:00",
        price: 20.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "requin-maroquinerie-2026",
        title: "Requin Chagrin - Mélancolie Tour",
        description: "Concert indie pop mélancolique à La Maroquinerie.",
        imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", // Indie Pop concert
        artistId: requin.id,
        venueId: maroquinerie.id,
        eventDate: new Date("2026-02-28"),
        eventTime: "20:00",
        price: 18.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "agar-agar-glazart-2026",
        title: "Agar Agar - Synth-Pop Party",
        description: "Soirée électro-pop dansante au Glazart.",
        imageUrl: "https://images.unsplash.com/photo-1571266028243-d220c6ce8f3d?w=800", // Électro/Synth-pop concert
        artistId: agar.id,
        venueId: glazart.id,
        eventDate: new Date("2026-03-20"),
        eventTime: "22:00",
        price: 20.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "foudre-boule-noire-2026",
        title: "Foudre! - Punk Explosion",
        description: "Concert garage punk explosif à La Boule Noire.",
        imageUrl: "https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=800", // Punk concert
        artistId: foudre.id,
        venueId: laBouleNoire.id,
        eventDate: new Date("2026-04-05"),
        eventTime: "21:00",
        price: 17.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "suzane-trabendo-2026",
        title: "Suzane - Pop Colorée",
        description: "Show pop/R&B énergique au Trabendo.",
        imageUrl: "https://images.unsplash.com/photo-1515191107209-c28698631303?w=800", // Pop/R&B concert
        artistId: suzane.id,
        venueId: trabendo.id,
        eventDate: new Date("2026-05-22"),
        eventTime: "20:00",
        price: 23.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "imperatrice-batofar-2026",
        title: "L'Impératrice - Disco Funk Night",
        description: "Soirée nu-disco sophistiquée sur le Batofar.",
        imageUrl: "https://images.unsplash.com/photo-1556848798-ee649b672584?w=800", // Disco/Funk concert
        artistId: orchestre.id,
        venueId: batofar.id,
        eventDate: new Date("2026-06-10"),
        eventTime: "21:30",
        price: 24.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "yseult-nouveau-casino-2026",
        title: "Yseult - Soul Experience",
        description: "Concert soul puissant au Nouveau Casino.",
        imageUrl: "https://images.unsplash.com/photo-1515191107209-c28698631303?w=800", // Soul/R&B concert
        artistId: yseult.id,
        venueId: nouveauCasino.id,
        eventDate: new Date("2026-05-28"),
        eventTime: "20:30",
        price: 22.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      // NOUVEAUX ÉVÉNEMENTS
      {
        slug: "molly-nilsson-silencio-2026",
        title: "Molly Nilsson - Synth Dreams",
        description: "Concert synth-pop intimiste au Silencio.",
        imageUrl: "https://images.unsplash.com/photo-1571266028243-d220c6ce8f3d?w=800", // Synth-Pop concert
        artistId: molly.id,
        venueId: silencio.id,
        eventDate: new Date("2026-03-10"),
        eventTime: "21:00",
        price: 19.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "idles-olympia-2026",
        title: "IDLES - Joy as an Act of Resistance",
        description: "Concert punk rock explosif à l'Olympia.",
        imageUrl: "https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=800", // Punk Rock concert
        artistId: idles.id,
        venueId: olympia.id,
        eventDate: new Date("2026-04-15"),
        eventTime: "20:00",
        price: 35.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "black-midi-elysee-2026",
        title: "Black Midi - Experimental Night",
        description: "Performance rock expérimentale à l'Élysée Montmartre.",
        imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800", // Experimental Rock concert
        artistId: blackMidi.id,
        venueId: elysee.id,
        eventDate: new Date("2026-05-12"),
        eventTime: "20:30",
        price: 28.0,
        ticketUrl: "https://www.seetickets.fr",
        status: "upcoming",
      },
      {
        slug: "squid-cigale-2026",
        title: "Squid - Art Rock Show",
        description: "Concert art rock innovant à La Cigale.",
        imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800", // Art Rock concert
        artistId: squid.id,
        venueId: cigale.id,
        eventDate: new Date("2026-06-01"),
        eventTime: "20:00",
        price: 30.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "shame-trianon-2026",
        title: "Shame - Post-Punk Intensity",
        description: "Concert post-punk énergique au Trianon.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800", // Post-Punk concert
        artistId: shame.id,
        venueId: trianon.id,
        eventDate: new Date("2026-04-28"),
        eventTime: "21:00",
        price: 25.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "cocaine-piss-gibus-2026",
        title: "Cocaine Piss - Noise Chaos",
        description: "Concert noise rock déjanté au Gibus.",
        imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800", // Noise Rock concert
        artistId: cocaine.id,
        venueId: gibus.id,
        eventDate: new Date("2026-03-18"),
        eventTime: "22:00",
        price: 15.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "clara-luciani-olympia-2026",
        title: "Clara Luciani - Cœur Tour",
        description: "Grande soirée pop française à l'Olympia.",
        imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", // Pop Française concert
        artistId: clara.id,
        venueId: olympia.id,
        eventDate: new Date("2026-05-20"),
        eventTime: "20:00",
        price: 38.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "therapie-taxi-gaite-2026",
        title: "Therapie TAXI - Hit Sale Tour",
        description: "Concert electro-pop festif à La Gaîté Lyrique.",
        imageUrl: "https://images.unsplash.com/photo-1571266028243-d220c6ce8f3d?w=800", // Electro-Pop concert
        artistId: therapie.id,
        venueId: gaite.id,
        eventDate: new Date("2026-04-08"),
        eventTime: "21:00",
        price: 22.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "pomme-trianon-2026",
        title: "Pomme - Consolation Tour",
        description: "Concert folk intimiste au Trianon.",
        imageUrl: "https://images.unsplash.com/photo-1516450137517-162bfbeb8dba?w=800", // Chanson/Folk concert
        artistId: pomme.id,
        venueId: trianon.id,
        eventDate: new Date("2026-06-15"),
        eventTime: "20:00",
        price: 28.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "angele-zenith-2026",
        title: "Angèle - Nonante-Cinq Tour",
        description: "Grand show pop au Zénith Paris.",
        imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", // Pop concert
        artistId: angele.id,
        venueId: zenith.id,
        eventDate: new Date("2026-07-05"),
        eventTime: "20:00",
        price: 45.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "pepite-bellevilloise-2026",
        title: "Pépite - Session Acoustique",
        description: "Performance intimiste à La Bellevilloise.",
        imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", // Indie Pop concert
        artistId: pépite.id,
        venueId: bellevilloise.id,
        eventDate: new Date("2026-03-22"),
        eventTime: "20:00",
        price: 17.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "vendredi-divan-2026",
        title: "Vendredi sur Mer - Nuit Étoilée",
        description: "Concert dream pop au Divan du Monde.",
        imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800", // Dream Pop concert
        artistId: vendredi.id,
        venueId: divan.id,
        eventDate: new Date("2026-05-03"),
        eventTime: "21:00",
        price: 21.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "agar-agar-concrete-2026",
        title: "Agar Agar - Electronight",
        description: "DJ set électro sur Concrete.",
        imageUrl: "https://images.unsplash.com/photo-1603190287605-e6ade32fa852?w=800", // Électro concert
        artistId: agar.id,
        venueId: concreteVenue.id,
        eventDate: new Date("2026-06-18"),
        eventTime: "23:00",
        price: 20.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "imperatrice-rex-2026",
        title: "L'Impératrice - Disco Rex",
        description: "Soirée funk disco au Rex Club.",
        imageUrl: "https://images.unsplash.com/photo-1556848798-ee649b672584?w=800", // Disco/Funk concert
        artistId: orchestre.id,
        venueId: rex.id,
        eventDate: new Date("2026-07-10"),
        eventTime: "22:00",
        price: 26.0,
        ticketUrl: "https://www.resident-advisor.net",
        status: "upcoming",
      },
      {
        slug: "molly-badaboum-2026",
        title: "Molly Nilsson - Late Night Session",
        description: "Concert synth-pop tardif à Badaboum.",
        imageUrl: "https://images.unsplash.com/photo-1571266028243-d220c6ce8f3d?w=800", // Synth-Pop concert
        artistId: molly.id,
        venueId: badaboum.id,
        eventDate: new Date("2026-04-03"),
        eventTime: "22:30",
        price: 18.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "fontaines-cigale-2026",
        title: "Fontaines D.C. - Romance Tour",
        description: "Concert post-punk à La Cigale.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800", // Post-Punk concert
        artistId: fontaines.id,
        venueId: cigale.id,
        eventDate: new Date("2026-06-25"),
        eventTime: "20:30",
        price: 32.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "idles-elysee-2026",
        title: "IDLES - Ultra Mono Live",
        description: "Soirée punk rock intense à l'Élysée Montmartre.",
        imageUrl: "https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=800", // Punk Rock concert
        artistId: idles.id,
        venueId: elysee.id,
        eventDate: new Date("2026-05-25"),
        eventTime: "21:00",
        price: 30.0,
        ticketUrl: "https://www.seetickets.fr",
        status: "upcoming",
      },
      {
        slug: "clara-trianon-2026",
        title: "Clara Luciani - Sainte Victoire",
        description: "Concert pop française au Trianon.",
        imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", // Pop Française concert
        artistId: clara.id,
        venueId: trianon.id,
        eventDate: new Date("2026-06-08"),
        eventTime: "20:00",
        price: 29.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "suzane-cigale-2026",
        title: "Suzane - SLP Tour",
        description: "Show pop/R&B à La Cigale.",
        imageUrl: "https://images.unsplash.com/photo-1450044804117-534ccd6e6a3a?w=800", // Pop/R&B concert
        artistId: suzane.id,
        venueId: cigale.id,
        eventDate: new Date("2026-07-02"),
        eventTime: "20:30",
        price: 27.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "yseult-olympia-2026",
        title: "Yseult - Brut Tour",
        description: "Grand concert soul/R&B à l'Olympia.",
        imageUrl: "https://images.unsplash.com/photo-1515191107209-c28698631303?w=800", // Soul/R&B concert
        artistId: yseult.id,
        venueId: olympia.id,
        eventDate: new Date("2026-06-22"),
        eventTime: "20:00",
        price: 36.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "shame-glazart-2026",
        title: "Shame - Drunk Tank Pink",
        description: "Concert post-punk au Glazart.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800", // Post-Punk concert
        artistId: shame.id,
        venueId: glazart.id,
        eventDate: new Date("2026-05-18"),
        eventTime: "21:00",
        price: 23.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "pomme-cigale-2026",
        title: "Pomme - Les Failles Cachées",
        description: "Concert folk/chanson à La Cigale.",
        imageUrl: "https://images.unsplash.com/photo-1516450137517-162bfbeb8dba?w=800", // Folk/Chanson concert
        artistId: pomme.id,
        venueId: cigale.id,
        eventDate: new Date("2026-07-08"),
        eventTime: "20:00",
        price: 30.0,
        ticketUrl: "https://www.fnac.com",
        status: "upcoming",
      },
      {
        slug: "black-midi-trabendo-2026",
        title: "Black Midi - Cavalcade Live",
        description: "Performance expérimentale au Trabendo.",
        imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800", // Experimental Rock concert
        artistId: blackMidi.id,
        venueId: trabendo.id,
        eventDate: new Date("2026-06-12"),
        eventTime: "20:30",
        price: 26.0,
        ticketUrl: "https://www.seetickets.fr",
        status: "upcoming",
      },
      {
        slug: "therapie-badaboum-2026",
        title: "Therapie TAXI - Soirée Dansante",
        description: "Concert electro-pop à Badaboum.",
        imageUrl: "https://images.unsplash.com/photo-1515175192010-cf3250992719?w=800", // Electro-Pop concert
        artistId: therapie.id,
        venueId: badaboum.id,
        eventDate: new Date("2026-05-10"),
        eventTime: "21:30",
        price: 20.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "wetleg-elysee-2026",
        title: "Wet Leg - Wet Dream Tour",
        description: "Concert indie rock à l'Élysée Montmartre.",
        imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800", // Indie Rock concert
        artistId: wetneg.id,
        venueId: elysee.id,
        eventDate: new Date("2026-06-05"),
        eventTime: "20:00",
        price: 28.0,
        ticketUrl: "https://www.seetickets.fr",
        status: "upcoming",
      },
      {
        slug: "squid-gaite-2026",
        title: "Squid - Bright Green Field",
        description: "Concert art rock à La Gaîté Lyrique.",
        imageUrl: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800", // Art Rock concert
        artistId: squid.id,
        venueId: gaite.id,
        eventDate: new Date("2026-07-12"),
        eventTime: "20:30",
        price: 24.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "jaguwar-international-2026",
        title: "Jaguwar - Garage Session",
        description: "Concert garage rock intimiste à L'International.",
        imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800", // Garage Rock concert
        artistId: jaguwar.id,
        venueId: international.id,
        eventDate: new Date("2026-04-20"),
        eventTime: "21:00",
        price: 14.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "meskerem-hasard-2026",
        title: "Meskerem Mees - Folk Acoustique",
        description: "Concert folk au Hasard Ludique.",
        imageUrl: "https://images.unsplash.com/photo-1516450137517-162bfbeb8dba?w=800", // Folk concert
        artistId: meskerem.id,
        venueId: fleche.id,
        eventDate: new Date("2026-05-14"),
        eventTime: "20:00",
        price: 18.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "requin-divan-2026",
        title: "Requin Chagrin - Indie Melancholy",
        description: "Concert indie pop au Divan du Monde.",
        imageUrl: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800", // Indie Pop concert
        artistId: requin.id,
        venueId: divan.id,
        eventDate: new Date("2026-04-16"),
        eventTime: "20:30",
        price: 19.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "lewsberg-mecanique-2026",
        title: "Lewsberg - Minimal Punk",
        description: "Concert post-punk à La Mécanique Ondulatoire.",
        imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800", // Post-Punk concert
        artistId: lewsberg.id,
        venueId: mecanique.id,
        eventDate: new Date("2026-05-07"),
        eventTime: "21:00",
        price: 16.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "foudre-badaboum-2026",
        title: "Foudre! - Punk Sauvage",
        description: "Concert garage punk à Badaboum.",
        imageUrl: "https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=800", // Punk concert
        artistId: foudre.id,
        venueId: badaboum.id,
        eventDate: new Date("2026-04-24"),
        eventTime: "22:00",
        price: 16.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
      {
        slug: "papooz-java-2026",
        title: "Papooz - Soft Evening",
        description: "Concert soft rock à La Java.",
        imageUrl: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=800", // Soft Rock concert
        artistId: papooz.id,
        venueId: laJava.id,
        eventDate: new Date("2026-06-16"),
        eventTime: "20:00",
        price: 18.0,
        ticketUrl: "https://www.dice.fm",
        status: "upcoming",
      },
      {
        slug: "cocaine-international-2026",
        title: "Cocaine Piss - Noise Attack",
        description: "Concert noise rock chaotique à L'International.",
        imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800", // Noise Rock concert
        artistId: cocaine.id,
        venueId: international.id,
        eventDate: new Date("2026-04-11"),
        eventTime: "22:00",
        price: 13.0,
        ticketUrl: "https://www.shotgun.live",
        status: "upcoming",
      },
    ]).returning();

    console.log(`✅ ${createdEvents.length} événements créés`);

    console.log("\n🎉 Seeding completed successfully!");
    console.log(`📊 Résumé:`);
    console.log(`   - 25 artistes underground/indépendants`);
    console.log(`   - 30 salles parisiennes`);
    console.log(`   - ${createdEvents.length} événements`);
    console.log(`   - Prix des places : 13€ - 45€`);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    throw error;
  }
}

seed()
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });